=begin
Author: Joe Phabmixay 
Purpose: Meant to remove unnecessary columns, either already generated by migrations or replaced by files
Variables:
    none
Date: 7/25/18
=end

class RemoveRedundantFields < ActiveRecord::Migration[5.2]
  def change
    remove_column :users, :password
    remove_column :users, :cart_id
    remove_column :users, :album_list
    remove_column :users, :friend_list
    remove_column :users, :user_id
    remove_column :images, :user_id
  end
end
